### ISSUE TITLE
Link do reset no email está errado

### ISSUE THREAD

**Issue by asfernandes** [pedrokehl/starter-nodejs-rest#1]
O link enviado está sem o /api.

E na minha opinião ficou estranho enviar esse email pois ele não reseta pra um password gerado, então não faz sentido sem um frontend.

**Comment by pedrokehl** [comment]
Opa,
Concordo com o que você falou sobre não fazer muito sentido sem um front-end, mas a ideia é trazer um back-end REST genérico, que será utilizado com um front-end a escolha do desenvolvedor que usar o starter.
Sobre a falta do API na rota, é pra ser assim, o front-end terá uma rota /reset/:username/:token, validará com o api/reset/:username/:token, caso OK, mostra um formulário para preencher a nova senha, e envia um post para api/reset com o body contendo o token que está na URL e a nova senha.

Estou pensando em criar um front-end de exemplo para ficar mais clara essa parte...
Mas sobre o que eu falei acima, tu vê algo de errado?

**Comment by asfernandes** [comment]
Faz sentido sim. Obrigado.
