### ISSUE TITLE
Registro de usuários

### ISSUE THREAD

**Issue by asfernandes** [pedrokehl/starter-nodejs-rest#2]
Ao registrar um usuário o sistema não considera o e-mail obrigatório e aceita e grava outros campos que o usuário passar.

**Comment by pedrokehl** [comment]
Eaí Adriano,
Na verdade, não estou fazendo esse tipo de validação ainda, pois a ideia do projeto, é deixar ele genérico, assim o desenvolvedor que utilizar o starter, escolherá quais campos deseja salvar, quais deseja deixar obrigatório, etc

**Comment by asfernandes** [comment]
Entendi. Pra mim que sou leigo em node/express/restful não fica claro onde e como isso poderia ser feito da melhor forma.

**Comment by pedrokehl** [comment]
Caso o projeto que você esteja trabalhando, seja um pouco mais fechado, com campos que serão salvos, e os obrigatórios bem definidos, assim como o tipo de cada campo... Eu recomendaria utilizar o mongoose\* (eu uso o driver do mongo direto, pois prefiro ter mais liberdade), que trata muito bem dessas suas necessidades.
Já se for um projeto mais aberto, tu pode colocar essas validações no repositório de usuário, ou no controller que tá fazendo o cadastro... Também há uma possibilidade muito bacana, que já vi gente fazer, quando há muitos tipos diferentes de validações, é criar um novo diretório, por exemplo "validations", e dentro dele criar um arquivo "user", aí nesse arquivo, tu terá tuas funções de validações, e antes de salvar, tu passa por ele. Vai muito do gosto de cada um, o node te dá uma grande liberdade.

*https://www.npmjs.com/package/mongoose
