### ISSUE TITLE
Folders name

### ISSUE THREAD

**Issue by WendellAdriel** [pedrokehl/starter-nodejs-rest#3]
Hey @pedrokehl, first of all, congrats!!

I just wanted to give an advice, most projects use:
- `server` for the `backend` folder
- `client` for the `frontend` folder

I think that you can follow this!!!
It's not a bit thing, just a personal opinion!! :wink:

**Comment by pedrokehl** [comment]
Thanks Wendell !

Funny fact: When I created these two directories, I couldn't remember what's the right names (server/client), so I just named them front/back. LOL
Thanks for reminding me that.

**Comment by WendellAdriel** [comment]
Nice @pedrokehl, if you want help with anything just let me know!!! :wink:
