### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by WendellAdriel** [pedrokehl/starter-nodejs-rest#4]
Hey @pedrokehl for small projects the `backend` folder structure is fine, but in bigger projects is better to use a structure separated by modules. I think that you can change to something like:

- `core` you can leave the files that are already there in this folder
- `config` you can leave the file that is already there in this folder
- `domains` you can put here a folder for each entity in your app (they can be used by many modules)
  - `user` the user entity, here you can create the `models` and `repositories` folders
- `support` you can put here files that can be used to all modules in your application
- `modules` you put here all the modules in your application
  - `auth` the authentication module, here you can create the `controllers`, `routes` and other folders with files that are specific for this module

**Comment by pedrokehl** [comment]
I agree with you, in this approach it's easier to work in bigger projects.
I will do this when I get some free time. haha
Thanks

**Comment by WendellAdriel** [comment]
Nice @pedrokehl, if you want help with anything just let me know!!! :wink:

**Comment by pedrokehl** [comment]
Closing since the main purpose of this project is to beginners learn nodeJS and easily start applications
